# Generated by Django 3.2.9 on 2021-12-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_orderitem_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherlineitem',
            name='product_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
